unit-tests added
fond-of/spryker-brand-companies-rest-api pull request #1
Opened 2019-11-07 11:06 UTC by SpiderDan98

2020-03-16 10:23 UTC, SpiderDan98 commented on composer.json
> +    "php-coveralls/php-coveralls": "^2.1",
Checked for possible versions

2020-04-01 09:55 UTC, daniel-rose requested changes

2020-04-01 09:55 UTC, daniel-rose commented on src/FondOfSpryker/Zed/BrandCompaniesRestApi/Business/BrandCompaniesRestApiBusinessFactory.php
> +     * @throws
WTF?

2020-04-01 11:44 UTC, daniel-rose approved these changes

2020-04-01 11:44 UTC, merged